var EnemyType = [
    {
        type:0,
        textureName:"res/images/enemy.png",
        HP:1,
        scoreValue:15
    },
    {
        type:1,
        textureName:"res/images/enemy.png",
        HP:2,
        scoreValue:40
    },
    {
        type:2,
        textureName:"res/images/enemy.png",
        HP:4,
        scoreValue:60
    },
    {
        type:3,
        textureName:"res/images/enemy.png",
        HP:6,
        scoreValue:80
    },
    {
        type:4,
        textureName:"res/images/enemy.png",
        HP:10,
        scoreValue:150
    },
    {
        type:5,
        textureName:"res/images/enemy.png",
        HP:15,
        scoreValue:200
    }
];
